import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  metadataBase: new URL("https://www.biohazards.net"),
  title: {
    default: "biohazards.net — Job Management & AI Documents for Biohazard Operators",
    template: "%s | biohazards.net",
  },
  description:
    "biohazards.net turns your site assessment into a professional quote, scope of work, or completion report — generated by AI, branded to your business. Built for biohazard cleaning operators across Australia.",
  keywords: [
    "biohazard cleaning software Australia",
    "biohazard job management",
    "crime scene cleaning software",
    "biohazard quote generator",
    "trauma cleaning business software",
  ],
  openGraph: {
    type: "website",
    locale: "en_AU",
    url: "https://www.biohazards.net",
    siteName: "biohazards.net",
    title: "biohazards.net — Job Management & AI Documents for Biohazard Operators",
    description:
      "From job site to signed quote in under 10 minutes. AI-powered document generation for Australian biohazard cleaning businesses.",
  },
  twitter: {
    card: "summary_large_image",
    title: "biohazards.net",
    description: "AI-powered job management for biohazard cleaning operators.",
  },
  robots: {
    index: true,
    follow: true,
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.variable}>
      <body>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
